### PR TITLE
Load scripts from configuration folder

### LINKED ISSUE #48: Load scripts from non-AppImage location
I'm interested in creating scripts for the PostProcessingPlugin but Cura is too complex to be built by a mere mortal and the plugin doesn't seem to load scripts that are just plain in the file system and is limited to only those in the AppImage.

Please add support to load user scripts from some user accessible location.

### PR DESCRIPTION
**Pull request by fieldOfView**
This PR creates a folder named "scripts" in the configuration folder and loads scripts placed in that folder in addition to the scripts in the application/plugin resources folder.

Fixes #48
Includes #44

### CODE REVIEW

**Comment by nallath** [comment]
CURA-4469

**Comment by alekseisasin** [comment]
When and why we are going to load scripts from files?
Will it affect cura version upgrade? ( in case if we want to move legacy files into a new version)

**Comment by nallath** [comment]
Won't  affect version upgrade as far as I can see. 
The main reason we want to do this is to enable users to add scripts to the post processing plugin. Right now this isn't possible if you run it from AppImage or mac build.

**Comment by diegopradogesto** [comment]
Testing this PR I'm getting errors when trying to import the script that is stored in the config folder:

`2017-10-31 16:13:44,448 - ERROR - UM.Logger.logException [76]: Exception: Exception occured while loading post processing plugin
2017-10-31 16:13:44,449 - ERROR - UM.Logger.logException [80]: Traceback (most recent call last):
2017-10-31 16:13:44,449 - ERROR - UM.Logger.logException [80]:   File "C:\...\Cura\cura\..\plugins\PostProcessingPlugin\PostProcessingPlugin.py", line 169, in _createView
2017-10-31 16:13:44,450 - ERROR - UM.Logger.logException [80]:     self.loadAllScripts(path)
2017-10-31 16:13:44,450 - ERROR - UM.Logger.logException [80]:   File "C:\...\Cura\cura\..\plugins\PostProcessingPlugin\PostProcessingPlugin.py", line 111, in loadAllScripts
2017-10-31 16:13:44,451 - ERROR - UM.Logger.logException [80]:     loaded_script = __import__("PostProcessingPlugin.scripts."+ script_name, fromlist = [script_name])
2017-10-31 16:13:44,451 - ERROR - UM.Logger.logException [80]: ModuleNotFoundError: No module named 'PostProcessingPlugin.scripts.BQ_PauseAtHeight'
`

Is it something that you need to fix?

**Comment by ChrisTerBeke** [comment]
Getting the same error as @diegopradogesto posted (copied BQ pause at height plugin to user scripts folder).

**Comment by fieldOfView** [comment]
I'll see if I can do a followup PR to fix this (since this branch is already merged I cannot add to it anymore)

**Comment by fieldOfView** [comment]
Fixed in #54

**Pull request merged**
